### ISSUE TITLE
All info om fordonen ska inte visas i listvyn

### ISSUE THREAD

**Issue by tollyx** [tollyx/Garage2#5]
Från uppgiftsinstruktionerna:

"Det skall finnas en översiktsvy där alla parkerade fordon visas med viss grunddata t.ex. Typ, RegNr, färg & parkeringstid"

**Comment by stekman08** [comment]
Kvar att fixa. Ändra att det inte är CheckInTime som visas utan diff mellan nu och CheckInTime = parkeringstid.

**Comment by stekman08** [comment]
Fixat.
