### ISSUE TITLE
Kvitto

### ISSUE THREAD

**Issue by tollyx** [tollyx/Garage2#9]
När man tar ut ett fordon så ska man få ett kvitto.

Kvittot ska innehålla:

* [x] Info om fordonet som var parkerat
* [x] In- & utcheckningstid
* [x] Hur länge de har parkerat
* [x] Pris för parkeringsperioden

Kvittot ska vara sin egna view.

Bonus: Gör kvittot utskriftsvänligt.

**Comment by Reza1000** [comment]
Fixed
